services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_notes_db
    ports:
      - "3306:3306"
    networks:
      - app-network

  app:
    build:
      context: .
    container_name: notez_container
    environment:
      MYSQL_PASSWORD: root
      MYSQL_HOST: mysql
      MYSQL_DATABASE: my_notes_db
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - mysql

networks:
  app-network:
    driver: bridge
