version: '3'

services:
  flask:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_URL=${DB_URL}
    volumes:
      - .:/app
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"