"""fix tables and audit logs

Revision ID: 7e42aa5c8ffc
Revises: ac4f7fc29e16
Create Date: 2024-11-08 12:32:30.229769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e42aa5c8ffc'
down_revision: Union[str, None] = 'ac4f7fc29e16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
